### PR TITLE
fix: outputs espace

### LINKED ISSUE #403: step set output string should be unescaped
Hi, I found act does not unescape the step outputs string, for example: 

> This workflow will be printed Hello 2%25 in act
>  It will be printed Hello 2% in Github Actions

```yaml
on:
  workflow_dispatch:
  push:
jobs:
  script:
    name: Print
    runs-on: ubuntu-latest
    steps:
      - name: Format message
        id: format
        uses: actions/github-script@v2
        with:
          script: |
            return {"message":"Hello 2%"}
      - name: Format message
        uses: actions/github-script@v2
        env:
          TEXT: ${{ fromJSON(steps.format.outputs.result).message }}
        with:
          script: |
            console.log('text', process.env.TEXT)
            // will be printed Hello 2%25 in act
            // will be printed Hello 2% in Github Actions
```

Github demo action log: https://github.com/theowenyoung/test-actions/runs/1331351240?check_suite_focus=true

### PR DESCRIPTION
**Pull request by theowenyoung**
fix #403

Hi, by the issue, I suppose that we should unescape the command string, I made a pr, please review it if you have time. Thanks!

### CODE REVIEW

**Comment by theowenyoung** [comment]
Hi, @cplee , sorry to bother you, but can you review this if you have time? Thanks a lot

**Comment by cplee** [comment]
@theowenyoung - change looks good, and I appreciate the tests!

What do you think about defining a list of escape strings and compiling/matching the list? Seems like an improvement over:

```var commandPatternEscapeChar1 *regexp.Regexp
var commandPatternEscapeChar2 *regexp.Regexp
var commandPatternEscapeChar3 *regexp.Regexp
var commandPatternEscapeChar4 *regexp.Regexp
var commandPatternEscapeChar5 *regexp.Regexp```

**Comment by theowenyoung** [comment]
@cplee , Thanks, I'll try to change the code, but I'm a jser, not good at golang, I'll see what I can do, Thanks

**Comment by theowenyoung** [comment]
@cplee Hi, I have edited the unescape function, use map list instead of multiple vars, and use `strings.replace ` instead of regex, please review it if you have time, Thanks!

**Review by cplee — APPROVED** [review]
lgtm

**Review by cplee — APPROVED** [review]

**Comment by theowenyoung** [comment]
@cplee Thanks for the quick review, hope a release version soon.

**Comment by theowenyoung** [comment]
Hi, @cplee ,  May I known what time of the next release version? A project of mine rely act and I need this feature. Thanks!

**Comment by cplee** [comment]
@theowenyoung - just published v0.2.17

**Pull request merged**
