### PR TITLE
Rough handling for local checkouts in composite actions

### PR DESCRIPTION
**Pull request by jsoref**
This seems to work for me for #1112

Tested with:

```sh
git clone git@github.com:check-spelling/lunr.js.git
git checkout spell-check
 ~/code/nektos/act/dist/local/act -W .github/workflows/spelling.yml --container-architecture linux/arm64 -s GITHUB_TOKEN=$GITHUB_TOKEN
```

### CODE REVIEW

**Comment by jsoref** [comment]
Note: I don't have the bandwidth to figure out how to make this do the right thing. So, it's more of a pointer which should hopefully help someone else fix this properly.

**Comment by ChristopherHX** [comment]
...Isn't this logically equivalent to `act --no-skip-checkout -W .github/workflows/spelling.yml --container-architecture linux/arm64 -s GITHUB_TOKEN=$GITHUB_TOKEN`?
The only issue with that command is, that act always pulls from github.com or the specified github instance.

_I checked the readme and saw that this new cli option is missing, but is released in act `v0.2.26`_

**Comment by jsoref** [comment]
It'd be better if the code properly stubbed checkout in composite actions...

**Comment by ChristopherHX** [comment]
> I would love to get rid of that section from readme

I would approve removing this section.

> It'd be better if the code properly stubbed checkout in composite actions...

Yes, we need a mock which calls the docker cp once it sees actions/checkout to the specified path and remove the docker cp from startcontainer. I don't depend on this local checkout functionality, so only low priority for me.

**Pull request closed without merging**
