### PR TITLE
Extend events support & add tests/examples

### LINKED ISSUE #179: how to trigger a tag event locally
act version 0.2.7

workflow:
```yml
name: postgres action 

on:
  push:
    branches:
      - master
    tags:
      - v*

jobs:
  build-and-push:
    runs-on: ubuntu-16.04
    timeout-minutes: 3
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: build and push image
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: byzanteam/nitrogen-postgres
        registry: ${{ secrets.DOCKER_REGISTRY }}
        tag_with_ref: true
```

tag.json
```json
{
    "ref": "refs/tags/v0.0.1"
}

```

log:
```
DEBU[0000] Loading workflows from '/PATH/.github/workflows' 
DEBU[0000] Reading workflow '/PATH/.github/workflows/main.yml' 
DEBU[0000] Using detected workflow event: push          
DEBU[0000] Planning event: push                         
DEBU[0000] Reading event.json from /PATH/tag.json 
DEBU[0000] Loading slug from git directory '/PATH/.git' 
DEBU[0000] Found revision: 7c6d9e0bd6b4fcd2dfe32296e8298ae4c32ac2d3 
DEBU[0000] Loading revision from git directory '/PATH/.git' 
DEBU[0000] Found revision: 7c6d9e0bd6b4fcd2dfe32296e8298ae4c32ac2d3 
DEBU[0000] HEAD points to '7c6d9e0bd6b4fcd2dfe32296e8298ae4c32ac2d3' 
DEBU[0000] HEAD matches refs/heads/master               
DEBU[0000] using github ref: refs/heads/master          
[postgres action/build-and-push] 🚀  Start image=node:12.6-stretch-slim
DEBU[0000] Loading slug from git directory '/PATH/.git' 
DEBU[0000] Found revision: 7c6d9e0bd6b4fcd2dfe32296e8298ae4c32ac2d3 
DEBU[0000] Loading revision from git directory '/PATH/.git' 
DEBU[0000] Found revision: 7c6d9e0bd6b4fcd2dfe32296e8298ae4c32ac2d3 
DEBU[0000] HEAD points to '7c6d9e0bd6b4fcd2dfe32296e8298ae4c32ac2d3' 
DEBU[0000] HEAD matches refs/heads/master               
DEBU[0000] using github ref: refs/heads/master          
[postgres action/build-and-push]   🐳  docker pull node:12.6-stretch-slim
```

questions:

1. how to trigger a tag event locally?
2. Is there an example of this?

### LINKED ISSUE #602: Issue: `act asdfasdfasdf` silently succeeds
## Act version
```
act version 0.2.20
```

## Expected behaviour

Any sort of error, and a non-successful status

## Actual behaviour
```
$ act asdfasdf; echo $?
0
```

## Workflow and/or repository

Any repo, as long as it has at least one workflow.

## Steps to reproduce

`act asdfasdfashjdgfkajhsgdf`

## `act` output

```
[mcsaucy@notacrook:~/act]$ act -v adsfasdf
DEBU[0000] Loading environment from /home/mcsaucy/act/.env 
DEBU[0000] Loading secrets from /home/mcsaucy/act/.secrets 
DEBU[0000] Loading workflows from '/home/mcsaucy/act/.github/workflows' 
DEBU[0000] Reading workflow '/home/mcsaucy/act/.github/workflows/push.yml' 
DEBU[0000] Reading workflow '/home/mcsaucy/act/.github/workflows/stale.yml' 
DEBU[0000] Reading workflow '/home/mcsaucy/act/.github/workflows/test-composite.yml' 
DEBU[0000] Reading workflow '/home/mcsaucy/act/.github/workflows/test-expressions.yml' 
DEBU[0000] Reading workflow '/home/mcsaucy/act/.github/workflows/test-if.yml' 
DEBU[0000] Planning event: adsfasdf
```

### LINKED ISSUE #671: Issue: Event type is not parsed from event file
## Act version

https://github.com/nektos/act/commit/8153dc92e5c34c51d02777b8274f05c399d3befc

## Expected behaviour

event type should be parsed from event file

## Actual behaviour

it defaults to push

## Workflow and/or repository

n/a

## Steps to reproduce

```sh
go run main.go -e pkg/runner/testdata/pull-request/event.json -W pkg/runner/testdata/pull-request/main.yaml -v
```

## `act` output

<details>
  <summary>Log</summary>

```sh
  ~/go/src/github.com/nektos/act cat/fix/event-json *4 ?1 ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────  3s cat@alpine-vm 11:53:1
❯ act -e pkg/runner/testdata/pull-request/event.json -W pkg/runner/testdata/pull-request/main.yaml -v
DEBU[0000] Loading environment from /home/cat/go/src/github.com/nektos/act/.env 
DEBU[0000] Loading secrets from /home/cat/go/src/github.com/nektos/act/.secrets 
DEBU[0000] Loading workflow '/home/cat/go/src/github.com/nektos/act/pkg/runner/testdata/pull-request/main.yaml' 
DEBU[0000] Reading workflow '/home/cat/go/src/github.com/nektos/act/pkg/runner/testdata/pull-request/main.yaml' 
DEBU[0000] Planning event: push                         
DEBU[0000] Reading event.json from /home/cat/go/src/github.com/nektos/act/pkg/runner/testdata/pull-request/event.json 
  ~/go/src/github.com/nektos/act cat/fix/event-json *4 ?1 ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────── cat@alpine-vm 12:02:5
❯
```

</details>

### PR DESCRIPTION
**Pull request by catthehacker**
changelog:
  - parse event name from `event.json`
  - add list of allowed event names
  - add test for every event

fixes #602
fixes #671
fixes #179

### CODE REVIEW

**Comment by FedorLap2006** [comment]
@catthehacker Any updates?

**Comment by catthehacker** [comment]
No, because I've been dying from toothache recently for past few weeks

**Comment by ChristopherHX** [comment]
Could we implement a mapping of event.json to event_name dynamically using the machine readable schema file and embed it on build? (source https://github.com/octokit/webhooks#readme)
[The schema file](https://unpkg.com/@octokit/webhooks-schemas/schema.json) has required keywords for all events, this would avoid maintaining a big cases series and is updated by github, not by act maintainers.
However it seems the schema file requires more properties to be available than your implementation.
These files of the repo seems to be the source of the webhook documentation, but in clean json.

**Comment by catthehacker** [comment]
I've had to deal few times with schemas, I don't have mental capacity for next few years to do that.

**Comment by catthehacker** [comment]
wip: https://github.com/catthehacker/act-fork/tree/cat/fix/event-json-plus

**Comment by mathrick** [comment]
@catthehacker: 

> @BlindChickens what feature are you looking for? Most of this is cosmetic stuff

This is, as far as I can tell, the only way to test a workflow such as the following:
```
on:
  pull_request:
    types: [synchronize]
```
Which is far from cosmetic, and would be important for validating conditional workflow logic through automated testing (something I'm trying to do right now).

**Comment by BlindChickens** [comment]
> > Hi, what is holding back this absolutely critical PR from merging my good sirs?
> 
> @BlindChickens what feature are you looking for? Most of this is cosmetic stuff

Sorry, somehow missed this comment. Like @mathrick said, that and https://github.com/nektos/act/issues/179

**Pull request closed without merging**
