### PR TITLE
Fix github SSH regex for missing .git extension

### PR DESCRIPTION
**Pull request by michaelbeaumont**
Of course the same issue fixed in https://github.com/nektos/act/pull/34 exists for SSH URLs.

### CODE REVIEW

**Comment by catthehacker** [comment]
Could you add a testcase for it?

**Comment by catthehacker** [comment]
```
=== RUN   TestFindGitSlug
    git_test.go:42: 
        	Error Trace:	git_test.go:42
        	Error:      	Not equal: 
        	            	expected: "nektos/act"
        	            	actual  : "nektos/act.git"
        	            	
        	            	Diff:
        	            	--- Expected
        	            	+++ Actual
        	            	@@ -1 +1 @@
        	            	-nektos/act
        	            	+nektos/act.git
        	Test:       	TestFindGitSlug
    git_test.go:42: 
        	Error Trace:	git_test.go:42
        	Error:      	Not equal: 
        	            	expected: "owner/repo"
        	            	actual  : "owner/repo.git"
        	            	
        	            	Diff:
        	            	--- Expected
        	            	+++ Actual
        	            	@@ -1 +1 @@
        	            	-owner/repo
        	            	+owner/repo.git
        	Test:       	TestFindGitSlug
--- FAIL: TestFindGitSlug (0.00s)
```

**Comment by michaelbeaumont** [comment]
@catthehacker thanks! done

**Review by catthehacker — APPROVED** [review]

**Review by cplee — APPROVED** [review]

**Comment by catthehacker** [comment]
@michaelbeaumont thanks for contributing ❤️

**Pull request merged**
