### PR TITLE
feat: support `GITHUB_REF_NAME` & `GITHUB_REF_TYPE`

### PR DESCRIPTION
**Pull request by thiskevinwang**
Closes https://github.com/nektos/act/issues/970

### CODE REVIEW

**Comment by KnisterPeter** [comment]
@thiskevinwang There is a test failing which checks if the env-vars are setup correctly. Your new vars have to be added there with expected values.

**Comment by thiskevinwang** [comment]
@KnisterPeter should be fixed 🤞 , waiting for CI now...

💭 It took me a bit to find the broken test. Is there an easy way to do this?
I ended up running `make test | tee testoutput.txt` and groking the output file a little bit... and eventually grep'ing for `--- FAIL` which found it.

**Comment by thiskevinwang** [comment]
> > thought_balloon It took me a bit to find the broken test. Is there an easy way to do this?
> > I ended up running `make test | tee testoutput.txt` and groking the output file a little bit... and eventually grep'ing for `--- FAIL` which found it.
> 
> Search for `FAIL: ` on GitHub CI log (when I'm lazy and pushing to PR) image or inside GoLand IDE (it hides successful tests) image image
> 
> I think VSCode test UI is still lacking since last time I tried it as well as `gopls`, so no idea about free alternatives

Thanks @catthehacker 

(Why was this comment marked as off topic 🤔 ???)

**Comment by ChristopherHX** [comment]
I would delete GITHUB_REF_NAME and GITHUB_REF_TYPE from the test env, like done for GITHUB_REF itself
https://github.com/nektos/act/blob/578ce6d803b5934f992fc2b2432bb3602a4b3e30/pkg/runner/step_test.go#L156

I only added ACT_OWNER to the workflow, so the tests doesn't fail in my fork due to env dependent tests. If you ask me Tests should set github.ref to a known value, then we can check if github.ref_name and github.ref_type matches.

**Review by ChristopherHX — APPROVED** [review]

**Review by KnisterPeter — APPROVED** [review]
Great

**Pull request merged**
