### PR TITLE
Fix path for local node12 actions

### LINKED ISSUE #185: local js action fails (uses: ./)
When developing a new JS action, I like to create a workflow within the same repo so I can test various use cases.  In such a case, I reference the local action with `- uses: ./` as defined in [the documentation](https://help.github.com/en/actions/building-actions/creating-a-javascript-action#example-using-a-private-action)

```yaml
on: [push]
jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: ./
        with:
          who-to-greet: 'Mona the Octocat'
``` 

Unfortunately, it fails with the following error: 

```
internal/modules/cjs/loader.js:628
|     throw err;
|     ^
| 
| Error: Cannot find module '/github/workspace/aws-instance-ripper/index.js'
|     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:625:15)
|     at Function.Module._load (internal/modules/cjs/loader.js:527:27)
|     at Function.Module.runMain (internal/modules/cjs/loader.js:839:10)
|     at internal/main/run_main_module.js:17:11 {
|   code: 'MODULE_NOT_FOUND',
|   requireStack: []
| }
``` 

It does work if I move the action code in an `action` subfolder and use it with `- uses: ./action`.

This can be reproduced with [the sample hello-world-javascript-action](https://github.com/actions/hello-world-javascript-action.git), you just need to add a basic workflow.

### PR DESCRIPTION
**Pull request by jromero**
This changes makes it so that the proper path is used when executing a local javascript (`node12`) action.

Additional minor changes:
- Updated Makefile
    - Updated `make test` to be functional by running expected `go test` task based on [README.md](https://github.com/nektos/act#building-from-source)
    - Added `make format` to format based on [CONTRIBUTING.md](https://github.com/nektos/act/blob/master/CONTRIBUTING.md#-styleguide)
    - Made `GITHUB_TOKEN` be set only once instead of re-executing `cat` per target.
- Update `expression_tests` to retain previous behaviour (when no file matched) now that a `package-lock.json` file exists in `testdata`.

Fixes #185

### CODE REVIEW

**Comment by jromero** [comment]
The changes here are minimal but the PR looks huge because of the node_modules. I can try making the testdata action a compiled version via ncc if that's desired.

**Comment by cplee** [comment]
@jromero - i'd rather not have the `node_modules` in the repo. can we come up with another option for this?

**Comment by jromero** [comment]
> @jromero - i'd rather not have the `node_modules` in the repo. can we come up with another option for this?

Yup I can compile it as mentioned above. Given that this is more or less a static javascript app the concern of having to update it via compilation seems very minimal.

I'll update the PR and squash it.

**Comment by jromero** [comment]
@cplee updated. Let me know what you think.

**Review by cplee — APPROVED** [review]
awesome @jromero 🎉

**Pull request merged**
