### PR TITLE
GitHub Enterprise support

### PR DESCRIPTION
**Pull request by ZauberNerd**
This is a continuation of @catthehacker  https://github.com/catthehacker/act-fork/tree/enterprise-github

* We've updated the GHE URLs, because the API and GraphQL URLs are different on GHE than on github.com
* We've updated the slug matching in common/git.go to match only the configured GHE instance

~~This is a draft for now, because we haven't tested it yet. We'll update and ping once we're ready to merge.~~

Closes https://github.com/nektos/act/issues/497

### CODE REVIEW

**Comment by ZauberNerd** [comment]
@cplee @catthehacker We've successfully executed act on our internal GHE and it works fine with the proposed changes.
Please review.

We are seeing one test failure in the powershell test but that seems also broken on `master`.

**Comment by cplee** [comment]
@ZauberNerd - tests shouldn't be failing on `master` - most recent PR from last night had all checks passing: https://github.com/nektos/act/pull/660/checks

**Comment by catthehacker** [comment]
https://github.com/nektos/act/pull/658/checks?check_run_id=2510198377#step:6:2676

```
[remote-action-js/test]   ☁  git clone 'https:///actions/hello-world-javascript-action' # ref=v1
[remote-action-js/test]   cloning https:///actions/hello-world-javascript-action to /home/runner/.cache/act/actions-hello-world-javascript-action@v1
[remote-action-js/test] Unable to clone https:///actions/hello-world-javascript-action refs/heads/v1: Get "https:///actions/hello-world-javascript-action/info/refs?service=git-upload-pack": http: no Host in request URL
time="2021-05-05T14:35:53Z" level=debug msg="Get \"https:///actions/hello-world-javascript-action/info/refs?service=git-upload-pack\": http: no Host in request URL"
time="2021-05-05T14:35:53Z" level=debug msg="Get \"https:///actions/hello-world-javascript-action/info/refs?service=git-upload-pack\": http: no Host in request URL"
[remote-action-js/test]   ❌  Failure - actions/hello-world-javascript-action@v1
time="2021-05-05T14:35:53Z" level=debug msg="Get \"https:///actions/hello-world-javascript-action/info/refs?service=git-upload-pack\": http: no Host in request URL"
time="2021-05-05T14:35:53Z" level=debug msg="Get \"https:///actions/hello-world-javascript-action/info/refs?service=git-upload-pack\": http: no Host in request URL"
Error:     runner_test.go:71: assertion failed: error is not nil: Get "https:///actions/hello-world-javascript-action/info/refs?service=git-upload-pack": http: no Host in request URL: /home/runner/work/act/act/pkg/runner/testdata/remote-action-js
=== RUN   TestRunEvent/local-action-docker-url
time="2021-05-05T14:35:53Z" level=debug msg="Loading workflows from '/home/runner/work/act/act/pkg/runner/testdata/local-action-docker-url'"
time="2021-05-05T14:35:53Z" level=debug msg="Reading workflow '/home/runner/work/act/act/pkg/runner/testdata/local-action-docker-url/push.yml'"
```

**Comment by KnisterPeter** [comment]
@catthehacker 
Locally I get this:
```markusw@lapi:~/source/act (ghe-support)$ go test -v -run TestStepContextExecutor github.com/nektos/act/pkg/runner
=== RUN   TestStepContextExecutor
=== RUN   TestStepContextExecutor/uses-and-run-in-one-step
*DRYRUN* [uses-and-run-in-one-step/test] 🚀  Start image=node:12.20.1-buster-slim
*DRYRUN* [uses-and-run-in-one-step/test]   🐳  docker run image=node:12.20.1-buster-slim platform= entrypoint=["/usr/bin/tail" "-f" "/dev/null"] cmd=[]
*DRYRUN* [uses-and-run-in-one-step/test] ⭐  Run Test
*DRYRUN* [uses-and-run-in-one-step/test]   ❌  Failure - Test
=== RUN   TestStepContextExecutor/uses-github-empty
*DRYRUN* [uses-github-empty/test] 🚀  Start image=node:12.20.1-buster-slim
*DRYRUN* [uses-github-empty/test]   🐳  docker run image=node:12.20.1-buster-slim platform= entrypoint=["/usr/bin/tail" "-f" "/dev/null"] cmd=[]
*DRYRUN* [uses-github-empty/test] ⭐  Run empty
*DRYRUN* [uses-github-empty/test]   ❌  Failure - empty
=== RUN   TestStepContextExecutor/uses-github-noref
*DRYRUN* [uses-github-noref/test] 🚀  Start image=node:12.20.1-buster-slim
*DRYRUN* [uses-github-noref/test]   🐳  docker run image=node:12.20.1-buster-slim platform= entrypoint=["/usr/bin/tail" "-f" "/dev/null"] cmd=[]
*DRYRUN* [uses-github-noref/test] ⭐  Run actions/checkout
*DRYRUN* [uses-github-noref/test]   ❌  Failure - actions/checkout
=== RUN   TestStepContextExecutor/uses-github-root
*DRYRUN* [uses-github-root/test] 🚀  Start image=node:12.20.1-buster-slim
*DRYRUN* [uses-github-root/test]   🐳  docker run image=node:12.20.1-buster-slim platform= entrypoint=["/usr/bin/tail" "-f" "/dev/null"] cmd=[]
*DRYRUN* [uses-github-root/test] ⭐  Run actions/checkout@v2
*DRYRUN* [uses-github-root/test]   ☁  git clone 'https:///actions/checkout' # ref=v2
*DRYRUN* [uses-github-root/test]   ✅  Success - actions/checkout@v2
=== RUN   TestStepContextExecutor/uses-github-path
*DRYRUN* [uses-github-path/test] 🚀  Start image=node:12.20.1-buster-slim
*DRYRUN* [uses-github-path/test]   🐳  docker run image=node:12.20.1-buster-slim platform= entrypoint=["/usr/bin/tail" "-f" "/dev/null"] cmd=[]
*DRYRUN* [uses-github-path/test] ⭐  Run sergioramos/yarn-actions/install@v6
*DRYRUN* [uses-github-path/test]   ☁  git clone 'https:///sergioramos/yarn-actions' # ref=v6
*DRYRUN* [uses-github-path/test]   ✅  Success - sergioramos/yarn-actions/install@v6
--- PASS: TestStepContextExecutor (0.88s)
    --- PASS: TestStepContextExecutor/uses-and-run-in-one-step (0.01s)
    --- PASS: TestStepContextExecutor/uses-github-empty (0.00s)
    --- PASS: TestStepContextExecutor/uses-github-noref (0.00s)
    --- PASS: TestStepContextExecutor/uses-github-root (0.45s)
    --- PASS: TestStepContextExecutor/uses-github-path (0.42s)
PASS
ok  	github.com/nektos/act/pkg/runner	0.891s
```

Since I'm new to go, can you give me a hint why this is failing on CI? I can't spot the difference in my setup.

**Comment by catthehacker** [comment]
Worked in CI now and works for me locally so I guess we can just call that one fail a fluke. LGTM

**Review by catthehacker — APPROVED** [review]

**Review by cplee — APPROVED** [review]

**Pull request merged**
