### PR TITLE
feat: support branches as GITHUB_REF

### LINKED ISSUE #67: run workflows with tag filters
Hi!

Thanks for the project, it helps a lot to debug issues and all that! Its awesome!

So, yesterday we had that github outage in which webhook weren't being delivered. I thought it would be a great idea to use `act` to deploy locally in these situations, but... my workflows have a tag filtering step, and seems like act always uses `master`.

Would you be interested in something to hack around that? In *theory*, just walk on files on `.git/refs/tags` and check if the contents of any of them match `.git/HEAD` contents and glue it together with act.

I'm working on a hacky-ish implementation BTW :)

### PR DESCRIPTION
**Pull request by caarlos0**
closes #67 

---

~~If you think this is a good addition, I'll work into fixing/adding tests and making the code cleaner :)~~ done.

tested it locally, it works!

### CODE REVIEW

**Comment by caarlos0** [comment]
Just now notice I was working on master on my fork... sorry about that...

thanks for accepting the PR 🤟

**Comment by caarlos0** [comment]
@cplee just out of curiosity, any plans for the next release?

**Comment by cplee** [comment]
@caarlos0 apologies for the delay...just released v0.1.3 🎉

**Comment by caarlos0** [comment]
awesome, thanks!

**Pull request merged**
