### PR TITLE
fix yay command

### PR DESCRIPTION
**Pull request by sloganking**
`-Syu` is for updating all packages. `-S` is for installing a package.

### CODE REVIEW

**Comment by cplee** [comment]
This was updated in #1355 

@hXtreme - can you comment on the change?

**Comment by hXtreme** [comment]
On arch it's bad practice to do partial upgrades, which is what happens if you only have `-S`, pr #1355 has a link to arch wiki explaining things in more detail.

**Comment by cplee** [comment]
@sloganking ☝️ ?

**Comment by sloganking** [comment]
I can't get any `yay -Syu` to work right now. As some other package fail to build. But `yay -Syu act` seems like it will install `act` correctly. And I think `yay -Syu act` is more correct in theory, even if it may make users run into more build issues with other packages. I'll close this PR for now.

**Pull request closed without merging**
