### PR TITLE
Act env

### PR DESCRIPTION
**Pull request by torbjornvatn**
This can be used to skip certain steps that you don't want to run locally
when testing. E.g. steps that sends messages to Slack channels on successful
builds etc.

### CODE REVIEW

**Comment by winksaville** [comment]
@torbjornvatn I fetched this change hoping it might resolve #416 as its related to handling of "env". Sepcifically in one step there is a `[t1/Linux build and test]   ⚙  ::set-env:: pythonLocation=/opt/hostedtoolcache/Python/3.6.12/x64` and in the next step a `path: ${{ env.pythonLocation }}` operation fails because env.pythonLocation is empty. But if I insert a step between the those steps that displays `env.pythonLocation` then the `path: ${{ env.pythonLocation }}` operation works.

I'd appreciate it if you could take a few minutes to look at #416 and potentially advise me where the problem might exist so as my search for a "real" solution might be faster.

Thanks in advance.

**Comment by torbjornvatn** [comment]
Hi @winksaville. 
Unfortunately I don't think that this particular PR will fix your problem as it's just a small addition to enable skipping of certain steps when running locally with Act.

But hopefully the fix I'm working on for #384 will solve your problem. I'll make sure to add a test case that reads the env in two successive steps.

As a workaround for now you might want to try using the `::set-output` syntax instead https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions#jobsjob_idoutputs

**Comment by cplee** [comment]
@torbjornvatn - this PR needs some attention now that #424 is merged

**Comment by torbjornvatn** [comment]
@cplee I've merged with master and fixed the conflicts now

**Review by cplee — APPROVED** [review]

**Pull request merged**
