### PR TITLE
Switch to `interface{}` instead of `map[string]...`

### LINKED ISSUE #284: (bug) fromJSON leading to a yaml unmarshal error
This part of my GitHub Action workflow is confirmed to work on Github, but not through act:

```yaml
strategy:
  matrix: ${{ fromJson(needs.deployments.outputs.deployments) }}
```

```bash
act -l
```

```
Error: yaml: unmarshal errors:
  line 153: cannot unmarshal !!str `${{ fro...` into map[string][]interface {}
```

The `deployments` output looks something like this:
```json
[
  { "region": "us", "key": "value" },
  { "region": "eu", "key": "value2" }
]
```

### LINKED ISSUE #330: cannot unmarshal error
https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions#fromjson

``` yml
name: build
on: push
jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - id: set-matrix
        run: echo "::set-output name=matrix::{\"include\":[{\"project\":\"foo\",\"config\":\"Debug\"},{\"project\":\"bar\",\"config\":\"Release\"}]}"
  job2:
    needs: job1
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{fromJson(needs.job1.outputs.matrix)}}
    steps:
      - run: echo ${{ matrix.project }}
```

```
Error: yaml: unmarshal errors:
  line 15: cannot unmarshal !!str `${{from...` into map[string][]interface {}
```

fromjson Not supported?

### LINKED ISSUE #450: Unmarshal error
When unmarshalling:
```yaml
strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.matrix.outputs.matrix) }}
```
I get the error:
```shell
Error: yaml: unmarshal errors:
  line 118: cannot unmarshal !!str `${{ fro...` into map[string][]interface {}
```

### LINKED ISSUE #540: Enhancement: Support matrix builds with dynamic input
## Describe feature

GitHub Actions has a neat feature to [create a matrix dynamically](https://github.blog/changelog/2020-04-15-github-actions-new-workflow-features/) based on the outputs of a previous job:

```yaml

name: Dynamic Matrix build

on:
  workflow_dispatch:
    inputs:
          x:
            description: 'Number of jobs on x-Axis'
            required: true
            default: '8'
          y:
            description: 'Number of jobs on y-Axis'
            required: true
            default: '4'

jobs:
  generate-matrix:
    name: "Generate matrix job specs"
    outputs:
      x: ${{ steps.generate-matrix.outputs.x }}
      y: ${{ steps.generate-matrix.outputs.y }}
    runs-on: ubuntu-latest
    steps:
      - name: generate-matrix
        id: generate-matrix
        run: |
          echo "::set-output name=x::[`seq -s , ${{ github.event.inputs.x }}`]"
          echo "::set-output name=y::[`seq -s , ${{ github.event.inputs.y }}`]"

  matrix:
      name: "Matrix job"
      runs-on: ubuntu-latest
      needs: [generate-matrix]
  
      strategy:
        fail-fast: false
        matrix:
          x: ${{ fromJson(needs.generate-matrix.outputs.x) }}
          y: ${{ fromJson(needs.generate-matrix.outputs.y) }}
      steps:
            - name: Perform job
              run: echo "${{matrix.x}}, ${{matrix.y}}"
```

`nektos/act` currently does not understand the dynamic input for the matrix dimensions as already reported in #450 - and errors out even if there is just one workflow file in the repository that is using this feature:

```bash
$ act -l
Error: yaml: unmarshal errors:
  line 37: cannot unmarshal !!str `${{ fro...` into []interface {}
  line 38: cannot unmarshal !!str `${{ fro...` into []interface {}
```

It would be amazing if `nektos/act` would be able to support dynamic matrix builds as well - or at least does not error out if it finds a workflow file with that syntax.

### PR DESCRIPTION
**Pull request by catthehacker**
Fixes issue with `env:` keys not being able to accept GitHub functions like `fromJSON()`
Fixes issue with matrixes not being able to be built with GitHub functions like `fromJSON()`

Fixed issues:
fixes #284
fixes #540
fixes #450
fixes #330

### CODE REVIEW

**Comment by catthehacker** [comment]
I'm actually surprised this works

**Review by cplee — APPROVED** [review]

**Comment by catthehacker** [comment]
`time="2021-05-24T20:36:23Z" level=debug msg="Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: docker.com/increase-rate-limit"`
😞

**Comment by pawelmhm** [comment]
I'm still seeing "cannot unmarshal error" in scrapy repo: https://github.com/scrapy/scrapy using act installed via go from latest master branch. Is it something about scrapy actions config?

**Comment by catthehacker** [comment]
@pawelmhm which workflow?

**Comment by catthehacker** [comment]
Checked `checks.yml` and `tests-ubuntu.yml`, both work fine on `act@master`

**Comment by pawelmhm** [comment]
interesting, I'm using ubuntu 18.04 I just run this

```
go install github.com/nektos/act@master
```

and then just run act in scrapy directory

```
[I] ~/s/scrapy ❯❯❯   (master) act
Error: yaml: unmarshal errors:
  line 37: cannot unmarshal !!str `${{ mat...` into map[string]string
```

**Comment by catthehacker** [comment]
run `which act` and `whereis act` ?

**Comment by pawelmhm** [comment]
[I] ~/s/scrapy ❯❯❯   (master) whereis act
act: /usr/local/bin/act
[I] ~/s/scrapy ❯❯❯   (master) which act
/usr/local/bin/act

**Comment by pawelmhm** [comment]
ah right that may be some old act version, let me double chck sorry

**Comment by pawelmhm** [comment]
I installed it properly, master version works fine, no yaml error. Thanks for this useful tool!

**Comment by catthehacker** [comment]
@sarah-liang this fix is not included in `v0.2.22`

**Comment by aurimasniekis** [comment]
> Fixes issue with matrixes not being able to be built with GitHub functions like fromJSON()

This looks like was broken. Because for example workflow as such does not work.

```yaml
name: "Dynamic Matix"

on:
  pull_request:
  push:

jobs:
  bar:
    name: Bar
    runs-on: ubuntu-latest
    steps:
      - id: output_data
        run: |
          echo '::set-output name=matrix::"{"package": ["a", "b"]}"'
    outputs:
      matrix: ${{ steps.output_data.outputs.matrix }}

  foo:
    name: Foo
    needs: [ bar ]
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJson(needs.bar.outputs.matrix) }}
    steps:
      - name: foo ${{ matrix.package }}
        run: |
          echo 'Matrix "${{ matrix.package }}" JSON: ${{ toJSON(matrix) }} ${{ needs.bar.outputs.matrix }}'
```

**Comment by catthehacker** [comment]
@aurimasniekis please create new issue

**Pull request merged**
