### PR TITLE
feat: support node20 runtime

### PR DESCRIPTION
**Pull request by freshollie**
Closes https://github.com/nektos/act/issues/1967

### CODE REVIEW

**Comment by freshollie** [comment]
Not sure I've done everything needed. Wanna see how CI deals with it

**Comment by harryzcy** [comment]
@freshollie Can you also include node18 in this PR?

**Comment by freshollie** [comment]
@cplee @ChristopherHX any reason not to merge this?

**Comment by harryzcy** [comment]
Is there a reason node_modules are included in Git, instead of installing them in the test?

**Comment by freshollie** [comment]
> A node20 test could be also without any node dependency, by using console.log / fs.writeSync(process.env.GITHUB_OUTPUT, 'out=test', { encoding: 'utf-8' }).

Makes sense, I just copied convention.

> The current approuch of adding node versions blows up the code of act and soon we have node12, node16, node20, node24 and we executute all with node
> I have had patched my act fork to ignore the number behind node.
There is definitely a better solution. This change for now allows people who have workflows on node20 to continue to use act.

**Review by cplee — APPROVED** [review]

**Comment by harryzcy** [comment]
Thank you for reviewing cplee.

If I understand correctly, the cron job for next release runs at the end of the month. But since node16 already reached EOL on Sep 11th, can you manually trigger the CI this time? Thanks.

**Pull request merged**
