### PR TITLE
Update README.md: Updated note about Apple Silicon

### PR DESCRIPTION
**Pull request by Freyja-Folkvangr**
Updated note about Apple Silicon
- Added link to Docker for Apple Silicon Release Candidate

### CODE REVIEW

**Review by catthehacker — APPROVED** [review]

**Comment by sr258** [comment]
There's even a regular release of Docker for Apple Silicon now.

**Comment by Freyja-Folkvangr** [comment]
Docker for Apple silicon now available

**Comment by hafizglasswall** [comment]
does it work out of the box now?

i dont see it working with apple silicon.

**Comment by catthehacker** [comment]
please ask on Gitter or create new issue

**Pull request closed without merging**
