### PR TITLE
Update Shell Tasks to match ScriptHandlerHelpers

### LINKED ISSUE #467: Doesn't correctly handle worker-level Powershell script runs
### Issue
Powershell 7 scripts do not run in native workers via `run:` step, and report a false positive of succeeding

### Steps to Reproduce
With the following simple config:
```yaml
name: Test
on:
  push:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - shell: pwsh
        run: |
          "this should work!"
          "Evidence" > /github/workspace/worked
```
and swapping in the official powershell worker (and using -r so the container doesn't disappear):
`act -rvP ubuntu-latest=mcr.microsoft.com/powershell:lts-ubuntu-18.04`
The result says success:
image

However upon inspecting the image via attaching a shell to the docker container the "evidence" file was not created:
image

And running the command manually in the container from shell shows an exec problem
image

Running the command using the `-f` format works fine however
image
image

### PR DESCRIPTION
**Pull request by JustinGrote**
Code: https://github.com/actions/runner/blob/main/src/Runner.Worker/Handlers/ScriptHandlerHelpers.cs

Docs: https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#using-a-specific-shell

Fixes #467
Replaces #466

Thanks to @catthehacker for the direction

### CODE REVIEW

**Comment by JustinGrote** [comment]
@cplee should be ready to review. Verified it works correctly on a runner with pwsh installed.
image

**Review by cplee — CHANGES_REQUESTED** [review]
@JustinGrote  - we've got a conflict here with #570 ... can you take a peek? 👀

**Comment by JustinGrote** [comment]
@cplee per the source link above I made mine match exactly what the actions runner does. I'll defer to @catthehacker if there's a specific issue that has to be addressed with act that isn't covered by the action runner cnofiguration.

**Comment by JustinGrote** [comment]
@cplee I see the other branch was already merged so I can rebase it to include the login shell, that's not a big deal and as @catthehacker describes in https://github.com/nektos/act/pull/570#issuecomment-801560100 using login shell is probably as good of an option as exists without breaking the way that it matches too extensively.

**Review by catthehacker — CHANGES_REQUESTED** [review]
`pkg/runner/act/sergioramos-yarn-actions-install@v6` should be removed

**Comment by JustinGrote** [comment]
@cplee uh, I don't think this test failure is me:
image

**Comment by cplee** [comment]
@JustinGrote - just pushed a fix to your branch...let's see if that gets it 🤞

**Pull request merged**
