### PR TITLE
Make envs available in if conditionals

### LINKED ISSUE #224: Support interpolation and ENV lookup in If: conditionals
I found my self wanting to use ENVs in if conditionals in my build and deployment workflows.
But act doesn't have the ENV map available in RunContext when `EvalBool` evaluates the conditional.

### PR DESCRIPTION
**Pull request by torbjornvatn**
This PR adds the possibility to use envs in if conditionals like this:
```yaml
- name: Some step
  if: env.SOMETHING   
  run: echo "GREAT!"
```
or like this: 
```yaml
- name: Some step
  if: ${{ env.RUNNING_LOCALLY != 'true' }}
  run: echo "GREAT!"
```

This is supported when the action runs on github, and I need it to avoid some slack messaging and deployment status updates when I test my actions locally with act.

fixes #224

### CODE REVIEW

**Comment by torbjornvatn** [comment]
I've tested all kinds of if conditional permutations in the github runner over here https://github.com/unacast/act/runs/642812337 to set up the test cases for this.

**Comment by cplee** [comment]
@torbjornvatn - this is fantastic, thanks for the contribution!  Would you mind rebasing the branch to match `master` and then i'll merge it

**Comment by torbjornvatn** [comment]
@cplee merged

**Comment by ethan797979** [comment]
I don’t want to do this.Thanks 




於 星期一, 5月 4, 2020, 21:53，Casey Lee <notifications@github.com> 寫道：




@torbjornvatn - this is fantastic, thanks for the contribution! Would you mind rebasing the branch to match master and then i'll merge it

**Comment by ethan797979** [comment]
Please help me to unsubscribe it.Thanks 




於 星期一, 5月 4, 2020, 21:15，Torbjørn Vatn <notifications@github.com> 寫道：


This PR adds the possibility to use envs in if conditionals like this:
- name: Some step
  if: env.SOMETHING   
  run: echo "GREAT!"
or like this:
- name: Some step
  if: ${{ env.RUNNING_LOCALLY != 'true' }}
  run: echo "GREAT!"
This is supported when the action runs on github, and I need it to avoid some slack messaging and deployment status updates when I test my actions locally with act.

fixes #224

You can view, comment on, or merge this pull request online at:

  https://github.com/nektos/act/pull/225

Commit Summary
   
   - Ignore .idea
   - Add Env to the RunContext vm so we can Evaluate and Interpolate `env.xx`
   - Make EvalBool support expressions more in line with the github runner
   - Merge origin/master into env_if
   - Turns out Boolean(value) is what github is doing after all
   - Add test for github context as well

File Changes
   
   -  M .gitignore (1) 
   -  M pkg/runner/expression.go (15) 
   -  M pkg/runner/expression_test.go (32) 
   -  M pkg/runner/run_context.go (18) 
   -  A pkg/runner/run_context_test.go (107) 

Patch Links:
   
   - https://github.com/nektos/act/pull/225.patch
   - https://github.com/nektos/act/pull/225.diff

**Pull request merged**
