### PR TITLE
add arch linux installation instructions

### PR DESCRIPTION
**Pull request by SirWindfield**
I've created an AUR package for act :)

### CODE REVIEW

**Comment by PaulWoitaschek** [comment]
It's outdated (0.1.3)

**Comment by cplee** [comment]
@SirWindfield - can you provide instructions on how to update the package?

**Comment by PaulWoitaschek** [comment]
Ideally there would just be a git package so it wouldn't need to be manually updated.

**Comment by cplee** [comment]
@PaulWoitaschek - agreed, but i don't know how to do that.  I don't have experience managing AUR packages.  Any chance you do and would want to help?

**Comment by SirWindfield** [comment]
There is: https://aur.archlinux.org/packages/act/

I am the maintainer. Will update in an hour or two when I am home.

**Comment by SirWindfield** [comment]
Done. Updated `act` and created a new package `act-git` that can be used to compile from the repository itself.

**Comment by cplee** [comment]
Thanks @SirWindfield!!

**Pull request merged**
