### PR TITLE
Simpler list view

### PR DESCRIPTION
**Pull request by lshamis**
Issue https://github.com/nektos/act/issues/260

Simplifies the output of `-l` into a more standard table view.
Also allows for ID discovery, to go with the `-j` flag.

For this repo:
===========================================
Before:
```
# act -l
    ╭──────╮ ╭──────╮
    │ lint │ │ test │
    ╰──────╯ ╰──────╯
            ⬇
 ╭─────────╮ ╭──────────╮
 │ release │ │ snapshot │
 ╰─────────╯ ╰──────────╯
```

After:
```
# act -l
ID        Stage  Name      
lint      0      Lint      
test      0      Test      
snapshot  1      Snapshot  
release   1      Release   
```

For alephzero repo:
===========================================

Before:
```
# act -l
 ╭──────────────────────────────╮ ╭───────────────────────────╮ ╭───────────────────╮ ╭──────────────────────╮ ╭──────────────────────────╮ ╭────────────╮ ╭──────────────╮ ╭──────────╮ ╭────────────────────────────╮ ╭───────────────╮ ╭─────────────╮ ╭────────────╮ ╭─────────────────────────────╮ ╭──────────────────╮ ╭────────╮
 │ Undefined Behavior Sanitizer │ │ Ubuntu Bionic Default GCC │ │ Address Sanitizer │ │ Include What You Use │ │ Ubuntu Focal Default GCC │ │ Clang-Tidy │ │ Alpine Clang │ │ Valgrind │ │ Ubuntu Focal Default Clang │ │ Code Coverage │ │ Alpine Musl │ │ Alpine GCC │ │ Ubuntu Bionic Default Clang │ │ Thread Sanitizer │ │ Format │
 ╰──────────────────────────────╯ ╰───────────────────────────╯ ╰───────────────────╯ ╰──────────────────────╯ ╰──────────────────────────╯ ╰────────────╯ ╰──────────────╯ ╰──────────╯ ╰────────────────────────────╯ ╰───────────────╯ ╰─────────────╯ ╰────────────╯ ╰─────────────────────────────╯ ╰──────────────────╯ ╰────────╯
```

After:
```
# act -l
ID            Stage  Name                          
ubsan         0      Undefined Behavior Sanitizer  
iwyu          0      Include What You Use          
tsan          0      Thread Sanitizer              
clang_tidy    0      Clang-Tidy                    
bionic_gcc    0      Ubuntu Bionic Default GCC     
alpine_musl   0      Alpine Musl                   
asan          0      Address Sanitizer             
focal_gcc     0      Ubuntu Focal Default GCC      
format        0      Format                        
cov           0      Code Coverage                 
alpine_gcc    0      Alpine GCC                    
valgrind      0      Valgrind                      
bionic_clang  0      Ubuntu Bionic Default Clang   
focal_clang   0      Ubuntu Focal Default Clang    
alpine_clang  0      Alpine Clang                  
```

### CODE REVIEW

**Comment by lshamis** [comment]
@cplee I'm not sure which test I'm breaking

**Comment by lshamis** [comment]
https://github.com/nektos/act/pull/383 had the same test breakage, which seems unrelated to the change.

**Comment by cplee** [comment]
@lshamis - i fixed the tests by rebasing. I'm a little sad to see the old view go away ...what do you think about keeping it with a `-g/--graph` option?

**Comment by lshamis** [comment]
```
/act# go run . -h
Run Github actions locally by specifying the event name (e.g. `push`) or an action name directly.

Usage:
  act [event name to run] [flags]

Flags:
  -a, --actor string           user that triggered the event (default "nektos/act")
  -b, --bind                   bind working directory to container, rather than copy
      --defaultbranch string   the name of the main branch
  -C, --directory string       working directory (default ".")
  -n, --dryrun                 dryrun mode
      --env-file string        environment file to read and use as env in the containers (default ".env")
  -e, --eventpath string       path to event JSON file
  -g, --graph                  draw workflows
  -h, --help                   help for act
  -j, --job string             run job
  -l, --list                   list workflows
  -P, --platform stringArray   custom image to use per platform (e.g. -P ubuntu-18.04=nektos/act-environments-ubuntu:18.04)
      --privileged             use privileged mode
  -p, --pull                   pull docker image(s) if already present
  -q, --quiet                  disable logging of output from steps
  -r, --reuse                  reuse action containers to maintain state
  -s, --secret stringArray     secret to make available to actions with optional value (e.g. -s mysecret=foo or -s mysecret)
      --secret-file string     file with list of secrets to read from (e.g. --secret-file .secrets)
  -v, --verbose                verbose output
  -w, --watch                  watch the contents of the local repo and run when files change
  -W, --workflows string       path to workflow file(s) (default "./.github/workflows/")


/act# go run . -l
ID        Stage  Name      
lint      0      Lint      
test      0      Test      
release   1      Release   
snapshot  1      Snapshot  


/act# go run . -g
    ╭──────╮ ╭──────╮
    │ Test │ │ Lint │
    ╰──────╯ ╰──────╯
            ⬇
 ╭──────────╮ ╭─────────╮
 │ Snapshot │ │ Release │
 ╰──────────╯ ╰─────────╯

```

**Comment by lshamis** [comment]
Yup, re-added the graph view.

Would you mind adding the label `hacktoberfest-accepted`?

**Review by cplee — APPROVED** [review]

**Pull request merged**
