### PR TITLE
docs: Expand the GITHUB_TOKEN section

### LINKED ISSUE #967: Enhancement: Add pointers for GITHUB_TOKEN to README
## Describe feature
When I started using act, I kept running into issues because I was missing the `GITHUB_TOKEN` and I couldn't be bothered to figure it out for a long time.

I believe this is such a common use-case that it bears spelling out briefly, what this token is and where to get it.

### PR DESCRIPTION
**Pull request by gzur**
When I started using act, it kept failing because I was missing the `GITHUB_TOKEN` and I couldn't be bothered to figure it out.

I was unsure how to get this token, so I did some research and wanted to lessen the confusion of future users.

I believe this is such a common use-case that it bears spelling out.

Fixes #967

### CODE REVIEW

**Review by KnisterPeter — APPROVED** [review]
Thank you

**Comment by gzur** [comment]
Something in the test suite is timing out.

Probably not related to my markdown 😂

**Comment by catthehacker** [comment]
If we are to extend the documentation regarding that, it would be good to include information that `GITHUB_TOKEN` can be logged in shell file history if not inserted through secure input and command is not prefixed with whitespace

**Comment by gzur** [comment]
> [...] `GITHUB_TOKEN` can be logged in shell file history if not inserted through secure input a

Though I agree with the sentiment, this is hardly the forum. Leaking credentials The problem is mentioned, but  - prefixing by whitespace is not a portable solution

> and command is not prefixed with whitespace

This is not true for every shell / platform

**Comment by gzur** [comment]
_Accidentally closed and re-opened this PR 😂_

I added a warning about leaking the `GITHUB_TOKEN` via shell history. I tried to be as concise as possible, since secure use of the shell is a huge topic and extremely platform specific and this README is hardly the forum for such a broad discussion.

**Review by catthehacker — APPROVED** [review]

**Comment by catthehacker** [comment]
> > If we are to extend the documentation regarding that, it would be good to include information that GITHUB_TOKEN can be logged in shell file history if not inserted through secure input and command is not prefixed with whitespace
> 
> I added a warning about leaking the `GITHUB_TOKEN` via shell history. I tried to be as concise as possible, since secure use of the shell is a huge topic and extremely platform specific and this README is hardly the forum for such a broad discussion. @catthehacker

Thanks, we are discussing better format for documentation which can have more descriptive information but for now this will suffice for sure.

**Review by ChristopherHX — APPROVED** [review]

**Review by cplee — APPROVED** [review]

**Pull request merged**
