### PR TITLE
Implement support for pre-/post-actions

### PR DESCRIPTION
**Pull request by ZauberNerd**
This PR needs https://github.com/nektos/act/pull/898 and https://github.com/nektos/act/pull/901 to be merged first.

Implemented here are:
- `pre`, `pre-if` for remote JavaScript actions
- `post`, `post-if` for local and remote JavaScript actions

### CODE REVIEW

**Comment by sp-ricard-valverde** [comment]
I've been working in a `post` and `post-if` implementation for `actions` and is working and related tests are passing in it's current state. I can open a PR for it if you want.

**Comment by sp-ricard-valverde** [comment]
Uploaded the changes to [this branch](https://github.com/sp-ricard-valverde/act/tree/feat/add-post-events)

**Comment by ZauberNerd** [comment]
> I've been working in a `post` and `post-if` implementation for `actions` and is functional and related tests are passing in it's current state. I can open a PR for it if you want.

@sp-ricard-valverde we're fine with either PR getting merged. Let's wait for @cplee and @catthehacker to review and decide which one better fits the overall architecture. In case #866 gets merged, @KnisterPeter and me will rebase / re-create this PR to add support for pre-actions.

**Comment by KnisterPeter** [comment]
@cplee @catthehacker @sp-ricard-valverde We are fine with our implementation now. We have implemented the `post`, `post-if` as well as `pre` and `pre-if` steps/logic.
As stated above we are waiting for review and a decision which implementation is better aligned to the overall architecture.

**Comment by KnisterPeter** [comment]
We added support for local actions as well. This does include the skipping over `pre` steps for local actions to be en-par with github-actions.

**Comment by KnisterPeter** [comment]
After some more tests against github-actions were are not sure if our implementation is sufficient.

We notied the following things:

Actions with a `pre` step:
- The pre step does run always, even if the step does have an `if` expression which evaluates to false
- The `with` settings are evaluated (conflicts with issue #597 and the changes in there)

Actions with only a `post` step:
- The post step is only executed if the main step is executed.

Actions with `pre` and `post` step:
- The pre step is always executed
- The post step is always executed
- Both get the `with` settings

We will stop working on this PR for now and reconsider an re-implementation (or continue the implementation in #866, but that may have the same issues).
We will start by creating smaller PRs which are preparing a state this can be implemented on (e.g. change Otto evaluation).

**Comment by sp-ricard-valverde** [comment]
> After some more tests against github-actions were are not sure if our implementation is sufficient.
> 
> We notied the following things:
> 
> Actions with a `pre` step:
> 
> * The pre step does run always, even if the step does have an `if` expression which evaluates to false
> * The `with` settings are evaluated (conflicts with issue [Issue: `with` fields should only be evaluated if `if` evaluates to true #597](https://github.com/nektos/act/issues/597) and the changes in there)
> 
> Actions with only a `post` step:
> 
> * The post step is only executed if the main step is executed.
> 
> Actions with `pre` and `post` step:
> 
> * The pre step is always executed
> * The post step is always executed
> * Both get the `with` settings
> 
> We will stop working on this PR for now and reconsider an re-implementation (or continue the implementation in #866, but that may have the same issues). We will start by creating smaller PRs which are preparing a state this can be implemented on (e.g. change Otto evaluation).

I think I have not faced the issues you encountered with the `post` implementation in #866 . I've identified some problems regarding the order of execution but I thin I have them solved and covered in test cases.

**Comment by KnisterPeter** [comment]
Even better

**Pull request closed without merging**
