### PR TITLE
Add code testing on MacOS

### PR DESCRIPTION
**Pull request by catthehacker**
Add code testing on MacOS. Performance is absolutely terrible on GHA (linux: <2 minutes, macos: >20 minutes) but hey! it works!

### CODE REVIEW

**Comment by cplee** [comment]
@catthehacker - is the slow part in the execution of the build or tests? Not sure I want to add a 20 min delay on each build 🤔

**Comment by catthehacker** [comment]
@cplee I know that MacOS runners on GitHub Actions have very bad performance especially with Docker running in VirtualBox machine, so I'm pretty sure that affects the testing phase and there shouldn't be any issue with building but I do not own any machine with MacOS so I can't tell how it looks like on normal Apple devices.
I'll try to get something up to verify it.

**Comment by catthehacker** [comment]
@cplee I couldn't find any way to test that myself locally yet. Would it be okay to merge PR if I remove dependency on MacOS test and add `continue-on-error: true` for MacOS?

**Review by cplee — APPROVED** [review]

**Comment by cplee** [comment]
@catthehacker - ready to merge once conflict is addressed.

**Comment by catthehacker** [comment]
@cplee Fixed conflicts and I've added `continue-on-error: true` to macos test as a failsafe so it doesn't break rest of workflow

**Review by cplee — APPROVED** [review]

**Pull request merged**
