### PR TITLE
Pull latest changes from ref using cached repo

### LINKED ISSUE #24: act fails when actions point to specific commits
This is absolutely bananas amazing work @nektos.

GitHub Actions documentation [seems to recommend](https://developer.github.com/actions/creating-github-actions/creating-a-new-action/#choosing-a-location-for-your-action) that we point to specific *commits* when relying on external actions from other repos:

> If you are developing an action for other people to use, GitHub recommends keeping the action in its own repository instead of bundling it with other application code. This allows you to version, track, and release the action just like any other software. Storing an action in its own repository makes it easier for the GitHub community to discover the action, narrows the scope of the code base for developers fixing issues and extending the action, and decouples the action's versioning from the versioning of other application code.

Consequently, the default [GitHub Action for Docker](https://github.com/actions/docker) hard codes the latest commit into my `main.workflow`:

```
action "GitHub Action for Docker-1" {
  uses = "actions/docker/cli@c08a5fc9e0286844156fefff2c141072048141f6"
  args = "build --tag=foo:bar ."
}
```

This seems quite attractive to me, and in keeping with the whole deployment-as-software-paradigm, because it isolates me from potentially breaking changes in the upstream action.

However, `act` doesn't seem to like this:

```
act
[GitHub Action for Docker-1] git clone 'https://github.com/actions/docker'
Error: reference not found
```

On a hunch, I deleted the hard-coded commit from the `main.workflow`, and voila, `act` does its thing.

```
action "GitHub Action for Docker-1" {
  uses = "actions/docker/cli
  args = "build --tag=foo:bar ."
}
```

```
act
```

Perhaps something is wrong in how the `main.workflow` gets parsed?

Let me know if you need a tighter reproducible example.

### PR DESCRIPTION
**Pull request by mheap**
Act switched from checking out a branch to checking out a hash in order to resolve #24 - see bc5c23e8e48ee1886ac274965852196d1ec3ba3f

This had a side effect of preventing `w.Pull()` from updating to the latest commit if a ref was a branch/tag and the repo already exists on disk.

This commit checks if input.Ref is equivalent to the resolved hash, and runs `r.Fetch()` and checks out the branch for `input.Ref` if it is different. `w.Pull()` can then pull the latest changes before we checkout `*hash` again like normal

### CODE REVIEW

**Comment by mheap** [comment]
@cplee What can I do to help get this reviewed and merged? It's blocking a workflow for our team

**Comment by mheap** [comment]
Thanks for merging so quickly! I'll keep an eye out for a new release soon 👍

**Comment by mheap** [comment]
Hey @cplee! Are you planning a release soon? Would love to stop using our custom build

**Comment by cplee** [comment]
@mheap - sorry for the delay. just released v0.2.10 🎉

**Pull request merged**
