### PR TITLE
-a now it is a -j

### PR DESCRIPTION
**Pull request by markyjackson-taulia**
Minor readme correction

### CODE REVIEW

**Comment by cplee** [comment]
`act -j` is to run a specific job...help me understand why this change is necessary 🤔

**Comment by markyjackson-taulia** [comment]
> `act -j` is to run a specific job...help me understand why this change is necessary 🤔

The `-a` in the readme no longer works and throws the following error:
```
Error: unknown shorthand flag: 'a' in -a
```

**Comment by cplee** [comment]
Where is there a reference to `-a` in the README? Sorry if i'm being dense...

**Comment by markyjackson-taulia** [comment]
wait a minute, have I been looking at the readme wrong!? Oh bloody hell!

**Pull request closed without merging**
