### PR TITLE
feat: load every environment from --env-file to workflow

### PR DESCRIPTION
**Pull request by jonyhy96**
As mentioned in #124 and #179, users are confused about the flag `--env-file` behavior.

So i think it is better to make it easier for user to use the .env file to set up some environments they want to use in the further workflow.

### CODE REVIEW

**Comment by cplee** [comment]
@jonyhy96 thanks for this PR.  i have some hesitation about assuming ALL environment variables should be accessible as GitHub secrets...seems like an assumption that could get folks in trouble, so i avoided that  in #124 

The idea was only those environment variables that you explicitly name (with `-s`) can be passed along.

Now this PR is trying to address a different problem from #179, about being able to override the environment variables that are used within the containers, specifically the GITHUB environment variables.

Couple thoughts...first, should this be a different flag to avoid overloading the current `--env-file` flag since these env vars are used differently...or if you like the name, add a new `--secrets-file` and change the current behavior to read secrets from that file?

Also, i don't really like how the path to env-file is passed through a new env variable and reread.  I'd rather those vars are read in from the CLI and passed in the runner context.

**Comment by jonyhy96** [comment]
Thanks for reply. 

> a new `--secrets-file` and change the current behavior to read secrets from that file

I prefer this way which is more clear to the user to use with `-s` flag.However, i think we could remove the `-s` flag and keep only `--secrets-file` flag which can be more easier for user to use secrets.(without supply two flags)

> Also, i don't really like how the path to env-file is passed through a new env variable and reread. I'd rather those vars are read in from the CLI and passed in the runner context.

And i totally agree with this, i use a new environment rather than context here because of i'm not sure if this pull request is my personally misunderstanding of the behavior. i will try to figure out a way to pass it through by a context.

**Comment by jonyhy96** [comment]
/cc @cplee  
Please review and let me know if anything wrong with the way i use the context.Value.
Thanks!

**Comment by cplee** [comment]
sorry @jonyhy96 - i misspoke.  I meant the run config, not context.  my bad!

I have a commit with what i had in mind and also has the `--secret-file` implemented.  I'd like to keep the existing `-s` as many folks like to pull secrets from their existing env (e.g. AWS_ACCESS_TOKEN) or pass a one off secret.

https://github.com/jonyhy96/act/pull/1

Thanks again!

**Comment by jonyhy96** [comment]
> [jonyhy96#1](https://github.com/jonyhy96/act/pull/1)

This looks good to me.I notice that [mergeMaps](https://github.com/jonyhy96/act/pull/1/files#diff-2c17edb7e58fb6d5704993cc8f5dc583L48) may overwrite environments in env-file by some built-in environments.Maybe we should mention that.
By the way, should i merge the pr to my fork repo?

**Comment by cplee** [comment]
@jonyhy96 yes, please merge to your branch

**Comment by jonyhy96** [comment]
> @jonyhy96 yes, please merge to your branch

Done

**Pull request merged**
