### PR TITLE
feat: support custom GITHUB_RUN_ID, GITHUB_RUN_NUMBER

### PR DESCRIPTION
**Pull request by theowenyoung**
Hi, I have a problem with `GITHUB_RUN_ID`.

 the action `actions/upload-artifact` need to use `GITHUB_RUN_ID`, but act define it to `1`, I suspect if there is a way to pass in a custom value, like use `.env` `GITHUB_RUN_ID`?

I submit a pr for this, would you give some advice?

```yaml
jobs:
  print:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/upload-artifact@v2
         with:
           name: test
           path: ./test.txt
```

### CODE REVIEW

**Review by cplee — APPROVED** [review]

**Comment by theowenyoung** [comment]
Hi, @cplee , Thanks for merging the pr. May I known what time of the next release version? A project of mine rely act and I need this feature. 

Thanks again!

**Comment by cplee** [comment]
@theowenyoung just released `0.2.15`

**Comment by prein** [comment]
How does one use it? Is it `--env GITHUB_RUN_ID=42` ?

**Comment by Cohen-Carlisle** [comment]
> How does one use it? Is it `--env GITHUB_RUN_ID=42` ?

For anyone looking for the answer to this question (three and a half years later), this is the indeed the way to use this feature!

**Pull request merged**
