### PR TITLE
Add config support, add survey on first launch when config doesn't exists

### PR DESCRIPTION
**Pull request by CatTheHacker**
Add config support, add survey on first launch when config doesn't exists

### CODE REVIEW

**Comment by cplee** [comment]
@CatTheHacker cool idea. I worry a bit though that the ways to config act get confusing. Any way to leverage existing .actrc support?

**Comment by CatTheHacker** [comment]
@cplee I was thinking of leaving `.actrc` as it is now and just build all options on top of config since config files tend to be cleaner and easier to read.
I was also thinking of making `config` subcommand as a way to interact with config file, so it could be either interactive via `act` or users could manually edit config file.
There is also a bit of context for that here: https://github.com/nektos/act/issues/107#issuecomment-760376329

**Comment by CatTheHacker** [comment]
A default config would look like this (or empty, then assume defaults from `act`). Parameters and `.actrc` would overwrite config file options
```yaml
actor: "nektos/act"
bind: false
defaultbranch: master
directory: .
dryrun: false
envfile: .env
eventpath:
graph: false
insecuresecrets: false
job:
list: false
platforms:
  ubuntu-latest: node:12
  ubuntu-18.04: ghcr.io/catthehacker/docker-images:ubuntu-nodejs-18.04
privileged: false
pull: false
quiet: false
reuse: false
secrets:
  A_SECRET: secret-value
  ANOTHER_SECRET: another-secret-value
secretfile:
verbose: false
watch: false
workflows: "./.github/workflows/"
```

**Comment by cplee** [comment]
It seems we could solve the UX issue without introducing another way of configuration (CLI args, env variables, .actrc)

How about this?
* Check if an explicit image was provided by `.actrc` or CLI arg
* If so, use it
* If not, prompt user about selecting a docker image to use (slim vs 20GB)
* Update `~/.actrc` with the docker image that they chose to use

**Comment by CatTheHacker** [comment]
@cplee yeah, that is possible and it's fine, I'll close this PR and make a new one with above logic for survey.

**Pull request closed without merging**
