### PR TITLE
ci: add Winget Releaser workflow

### LINKED ISSUE #1146: Enhancement: Ability to install act package into Windows OS (via winget for example).
## Describe feature
It would be great to download and use this package into Windows OS. 
Distribute it via winget (official windows package manager) will allow more developers to use act. 

In terms of advertisement, it would be great also from the https://formulae.brew.sh/formula/act#default redirect to winget for windows user (as many tutorials about act already redirect directly to brew page).

### PR DESCRIPTION
**Pull request by sitiom**
[This action](https://github.com/vedantmgoyal2009/winget-releaser) automatically generates manifests for Winget Community Repository ([microsoft/winget-pkgs](https://github.com/microsoft/winget-pkgs)) and submits them.

**Before merging this:**
1. Add a **classic** PAT with `public_repo` scope as a repository secret named `WINGET_TOKEN`.

example

2. Fork https://github.com/microsoft/winget-pkgs under @nektos. The action will use that fork for making a branch and creating a PR with the upstream [winget-pkgs](https://github.com/microsoft/winget-pkgs) repository on every release.
3. Install [Pull](https://github.com/apps/pull) on the winget-pkgs fork to ensure that it is constantly updated.

You can test out the action inputs in this [playground](https://bittu.eu.org/docs/wr-playground).

If you want to see an example of a PR created using this action, see [microsoft/winget-pkgs/pulls (Pull request has been automatically created using 🛫 WinGet Releaser)](https://github.com/microsoft/winget-pkgs/pulls?q=is%3Apr+sort%3Aupdated-desc+Pull+request+has+been+automatically+created+using+%F0%9F%9B%AB+WinGet+Releaser).

- Resolves #1146

### CODE REVIEW

**Comment by cplee** [comment]
Thanks @sitiom  for the details instructions ✅

**Review by cplee — APPROVED** [review]

**Comment by sitiom** [comment]
@vedantmgoyal2009 any idea why the workflow failed? https://github.com/nektos/act/actions/runs/4299439431/jobs/7494726051#step:2:113

**Comment by vedantmgoyal2009** [comment]
I guess the token permissions are not correct.

**Comment by sitiom** [comment]
> I guess the token permissions are not correct.

@cplee

**Comment by cplee** [comment]
image


image

**Comment by cplee** [comment]
The token permissions were correct...but the user (@nektos-ci) wasn't granted access to the fork 🤦 

Fixed and reran successfully: https://github.com/nektos/act/actions/runs/4299439431/jobs/7517109667

**Comment by sitiom** [comment]
Oh great, I already had a PR manually merged though 😅 (https://github.com/microsoft/winget-pkgs/pull/98056). You can close the opened PR for now: https://github.com/microsoft/winget-pkgs/pull/98167

**Comment by cplee** [comment]
Done!

**Comment by sitiom** [comment]
Now it works:
- https://github.com/microsoft/winget-pkgs/pull/101309

**Pull request merged**
