### PR TITLE
feat: add check for newer versions

### PR DESCRIPTION
**Pull request by cplee**
Notify user when a newer version of `act` is available. Support disabling of version check by setting environment variable `ACT_DISABLE_VERSION_CHECK=1`

### CODE REVIEW

**Review by KnisterPeter — COMMENTED** [review]
Looks good.
I have two questions:

1. The logger does output only text. If act is started with '--json' it should respect that. Otherwise the log would not be parsable
2. Why is the go-git patch by ZauberNerd removed?

**Comment by cplee** [comment]
Good catch @KnisterPeter . I updated to honor the `--json` for log format. Also reverted the change to go.mod (I was having issues with that patch and wasn't sure it was still needed?)

**Review by KnisterPeter — APPROVED** [review]
👍

**Comment by KnisterPeter** [comment]
We should check with @ZauberNerd.
What where the issues?

**Comment by cplee** [comment]
It was looking for tag `v5.4.3` in his fork, which didn't exist

**Comment by cplee** [comment]
@ChristopherHX - updated to keep the source version aligned with release version. This will avoid alerting on new versions if  built from source...unless there is in fact a new version available. Fixed #1069 too...

**Review by KnisterPeter — APPROVED** [review]

**Comment by ZauberNerd** [comment]
Oh, I rebased my PR https://github.com/go-git/go-git/pull/485 last month, that's probably why it couldn't find the tag anymore.

**Pull request merged**
